# Composeファイルのバージョンを指定
version: '3.3'

# 以下で各コンテナの設定を行う
services:
  front:
    # サービスのベースイメージにDockerfileを指定
    build: .
    command: bash -c " yarn install && yarn run dev"
    # 値を永続化
    volumes:
      - .:/usr/src/app
    # 公開ポート番号を指定
    ports:
      - 3000:3000
